# Generated by Django 5.0.3 on 2026-04-02 01:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('investments', '0003_asset_provider_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('condition', models.CharField(choices=[('ABOVE', 'Price is above'), ('BELOW', 'Price is below')], default='ABOVE', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('FIRED', 'Fired'), ('PAUSED', 'Paused')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='investments.asset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_alerts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
