# Generated by Django 5.0.3 on 2026-03-31 23:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], default='BUY', max_length=4)),
                ('quantity', models.DecimalField(decimal_places=8, help_text='Amount of the asset traded.', max_digits=20)),
                ('price_at_transaction', models.DecimalField(decimal_places=8, help_text='Price of the asset at the moment of the transaction.', max_digits=20)),
                ('fees', models.DecimalField(decimal_places=8, default=0, help_text='Transaction fees if applicable.', max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of when the transaction was recorded.')),
                ('asset', models.ForeignKey(help_text='The financial instrument being traded.', on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='investments.asset')),
                ('portfolio', models.ForeignKey(help_text='The portfolio where this transaction belongs.', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='investments.portfolio')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
