# Generated by Django 5.0.3 on 2026-03-31 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0002_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='provider_id',
            field=models.CharField(blank=True, help_text="ID used by the price provider (e.g., 'bitcoin' for CoinGecko)", max_length=100, null=True),
        ),
    ]
