# Generated by Django 5.0.3 on 2026-04-05 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0003_asset_provider_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='investments.asset')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['asset', 'timestamp'], name='investments_asset_i_e878c5_idx')],
            },
        ),
    ]
