# Generated by Django 5.0.3 on 2026-04-12 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_managers_remove_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pdf_downloads',
            field=models.IntegerField(default=0),
        ),
    ]
