import logging
from decimal import Decimal

from django.conf import settings

logger = logging.getLogger(__name__)

import io
from datetime import datetime

import redis
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

redis_client = redis.from_url(settings.REDIS_URL)


class PriceService:
    """
    Service layer to handle asset price retrieval from high-speed cache (Redis).
    """

    @staticmethod
    def get_current_price(asset_symbol):
        """
        Retrieves the latest price for a given asset symbol from Redis.

        Args:
            asset_symbol (str): The ticker symbol (e.g., 'BTC', 'ETH').

        Returns:
            Decimal: The current price if found in cache, None otherwise.
        """
        try:
            price = redis_client.get(f"price_{asset_symbol.upper()}")
            if price:
                return Decimal(price)
        except Exception as e:
            logger.error(
                "Failed to fetch price from Redis for symbol %s: %s", asset_symbol, e
            )

        return None


class PortfolioReportService:
    """
    Service responsible for generating professional PDF reports
    for a specific user portfolio.
    """

    @staticmethod
    def generate_pdf(portfolio):
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=letter)
        elements = []

        # Styles
        styles = getSampleStyleSheet()
        title_style = styles["Heading1"]
        subtitle_style = styles["Heading3"]
        normal_style = styles["Normal"]

        # 1. Header & Title
        elements.append(Paragraph("EquiFlow Financial Report", title_style))
        elements.append(Paragraph(f"Portfolio: {portfolio.name}", subtitle_style))
        elements.append(
            Paragraph(
                f"Generated on: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
                normal_style,
            )
        )
        elements.append(Spacer(1, 12))

        # 2. Financial Summary Snapshot
        elements.append(Paragraph("Financial Summary", subtitle_style))
        summary_data = [
            ["Total Balance", f"{portfolio.total_balance:,.2f} {portfolio.currency}"],
            [
                "Total Profit/Loss",
                f"{portfolio.total_profit_loss:,.2f} {portfolio.currency}",
            ],
        ]
        summary_table = Table(summary_data, colWidths=[150, 150])
        summary_table.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (0, -1), colors.whitesmoke),
                    (
                        "TEXTCOLOR",
                        (1, 1),
                        (1, 1),
                        colors.green
                        if portfolio.total_profit_loss >= 0
                        else colors.red,
                    ),
                    ("GRID", (0, 0), (-1, -1), 1, colors.grey),
                    ("FONTNAME", (0, 0), (-1, -1), "Helvetica-Bold"),
                    ("PADDING", (0, 0), (-1, -1), 6),
                ]
            )
        )
        elements.append(summary_table)
        elements.append(Spacer(1, 20))

        # 3. Assets Breakdown Table
        elements.append(Paragraph("Assets Breakdown", subtitle_style))

        # Table Headers
        data = [["Asset", "Quantity", "Avg. Price", "Current Value", "Profit/Loss"]]

        # Table Rows from PortfolioAsset
        for item in portfolio.assets.all():
            data.append(
                [
                    item.asset.symbol,
                    f"{item.quantity:.4f}",
                    f"{item.average_purchase_price:.2f}",
                    f"{item.current_value:.2f}",
                    f"{item.profit_loss:.2f}",
                ]
            )

        asset_table = Table(data, colWidths=[80, 80, 100, 100, 100])
        asset_table.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, 0), colors.cadetblue),
                    ("TEXTCOLOR", (0, 0), (-1, 0), colors.whitesmoke),
                    ("ALIGN", (0, 0), (-1, -1), "CENTER"),
                    ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                    ("BOTTOMPADDING", (0, 0), (-1, 0), 12),
                    ("BACKGROUND", (0, 1), (-1, -1), colors.beige),
                    ("GRID", (0, 0), (-1, -1), 1, colors.grey),
                ]
            )
        )

        elements.append(asset_table)

        # 4. Footer
        elements.append(Spacer(1, 30))
        elements.append(
            Paragraph(
                "This report was generated by EquiFlow PRO. Financial data may have a slight delay.",
                styles["Italic"],
            )
        )

        # Build PDF
        doc.build(elements)
        buffer.seek(0)
        return buffer
